name: Lighthouse Performance Check
on: [push, pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Audits
        run: |
          mkdir reports
          websites=( "https://himalayanflavor.onlineorder.site" "https://site2.com" "https://site3.com" )
          for site in "${websites[@]}"; do
            echo "Running Lighthouse audit for $site"
            site_name=$(echo $site | sed 's/https:\/\///g')
            lighthouse "$site" \
              --chrome-flags="--headless --no-sandbox" \
              --output json \
              --output html \
              --output-path="reports/$site_name.report"  # Sets base path for both JSON and HTML outputs
            
            # Check the JSON result for TTI
            json_report_path="reports/$site_name.report.json"
            if [ -f "$json_report_path" ]; then
              load_time=$(cat "$json_report_path" | jq '.audits["interactive"].numericValue')
              
              # Convert milliseconds to seconds
              load_time_in_seconds=$(echo "$load_time / 1000" | bc -l)
              
              if (( $(echo "$load_time_in_seconds > 10" | bc -l) )); then
                echo "❌ $site took more than 10 seconds to fully load: ${load_time_in_seconds}s"
                exit 1  # Fail the action if load time is over 10 seconds
              else
                echo "✅ $site loaded in ${load_time_in_seconds}s"
              fi
            else
              echo "⚠️ JSON report for $site not found at $json_report_path"
              exit 1  # Fail if JSON report is missing
            fi
          done
        shell: bash

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: reports/

      - name: Send Slack Notification
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "⚠️ Lighthouse audit failed for one or more websites: load time exceeded 10s or reports missing. Check the reports for details."
          }' $SLACK_WEBHOOK_URL
